### ISSUE TITLE
Linking fails in a project with Elastic APM iOS package (both SPM)

### ISSUE THREAD

**Issue by crownvic** [appmetrica/appmetrica-sdk-ios#11]
### 📚 AppMetrica SDK Version

5.1.0

### 🛠️ Xcode Version

Version 15.3 (15E204a)

### 📱 Device Information

iPhone 15 simulator iOS 17.4 (21E213)

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

AppMetrica is working great in my project. Now I need to add Elastic APM Agent. I tried adding it through SPM from here: https://github.com/elastic/apm-agent-ios (version 1.0.0). But when I build the project (doesn't matter if it's debug or release mode), I get these errors:

`duplicate symbol '_protobuf_c_buffer_simple_append' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_empty_string' in:
   hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_enum_descriptor_get_value' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_enum_descriptor_get_value_by_name' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_check' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_descriptor_get_field' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_descriptor_get_field_by_name' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_free_unpacked' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_get_packed_size' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_init' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_pack' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_pack_to_buffer' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_message_unpack' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_service_descriptor_get_method_by_name' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_service_destroy' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_service_generated_init' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_service_invoke_internal' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_version' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
duplicate symbol '_protobuf_c_version_number' in:
    hidden/Build/Products/Debug-iphonesimulator/AppMetrica_Protobuf.o
    hidden/Build/Products/Debug-iphonesimulator/CrashReporter.o
ld: 19 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Since I'm using Firebase and other Objective-C packages in the project, I have these "other linker flags" set up:
* For debug builds: -ObjC -ld_classic -Wl
* For release builds: just -ObjC

### 🔍 Reproducing the issue

1. Add AppMetrica to the project via SPM (it should compile fine)
2. Add at least -ObjC flag to "Other Linker Flags" in project's build settings
3. Add https://github.com/elastic/apm-agent-ios (version 1.0.0) via SPM and try to build the project

**Comment by GLinnik21** [comment]
Hello. I just want to make it clear. Does it reproduce only with the `-ObjC` flag present in the linker options?

**Comment by crownvic** [comment]
> Hello. I just want to make it clear. Does it reproduce only with the `-ObjC` flag present in the linker options?

Well, I created a new empty app project, added AppMetrica, then added Elastic APM Agent, and it also fails without the '-ObjC' flag as well.

**Comment by Sergey70** [comment]
The issue has been fixed and will be available in version 5.9.0, releasing in the next few days.

Thank you for your patience!
