### ISSUE TITLE
CocoaPods version doesn't compile, since no visible @interface for 'AMARequestParameters' 

### ISSUE THREAD

**Issue by larryonoff** [appmetrica/appmetrica-sdk-ios#12]
### 📚 AppMetrica SDK Version

5.1.0

### 🛠️ Xcode Version

Version 15.2-15.3

### 📱 Device Information

iPhone simulato, iOS 17.2

### ⚙️ Installation Method

CocoaPods

### 📝 Description

The project with AppMetrica doesn't compile since the error: `No visible @interface for 'AMARequestParameters' declares the selector 'initWithApiKey:attributionID:requestID:applicationState:inMemoryDatabase:'`

<img width="919" alt="Screenshot 2024-03-29 at 10 03 29" src="https://github.com/appmetrica/appmetrica-sdk-ios/assets/372616/8098beb0-c914-41aa-8dc0-219cfb88ebc2">

### 🔍 Reproducing the issue

1. Install AppMetrica 5.1.0 via Cocoapods
2. Create any swift file with `import AppMetricaCore`
3. Compile
4. The error occurs

**Comment by Sergey70** [comment]
Thank you for the update.

Could you please provide the Podfile.lock file to ensure accurate resolution of dependencies?

There is a known issue where `AppMetricaNetwork` of version 5.0.0 is incompatible with `AppMetricaCore` 5.1.0. 
To maintain compatibility, please ensure that the version of `AppMetricaNetwork` is explicitly set to match `AppMetricaCore`.

```ruby
   pod 'AppMetricaCore', '5.1.0'
   pod 'AppMetricaNetwork', '5.1.0'
```

Starting from version 5.2.0, this issue will be resolved, and there will no longer be a need to explicitly specify the version of `AppMetricaNetwork`.

**Comment by larryonoff** [comment]
@Sergey70 thanks for the quick update.

We use AppMetrica in our SDKs. So it's in our podspec. I have found two issues here.
1. AppMetrica was 5.0.0, not 5.1.0
2. AppMetricaNetwork was not present in the podspec.

Now issue is resolved for us
