### ISSUE TITLE
How to separate AppMetrica activationby the app itself and the 3rd party SDK?

### ISSUE THREAD

**Issue by aserdobintsev** [appmetrica/appmetrica-sdk-ios#15]
### 📚 AppMetrica SDK Version

5.2.0

### 🛠️ Xcode Version

Version 15.3 (15E204a)

### 📱 Device Information

iPhone 14 Pro, iOS 17.4.1

### ⚙️ Installation Method

CocoaPods

### 📝 Description

I've used AppMetrica old version i.e. YandexMobileMetrica and it works.

After updating to AppMetrica 5.2.0 the app start crashes because of 3rd party sdk Yookassa uses AppMetrica too for themselves and activates AppMetrica too:
https://git.yoomoney.ru/projects/SDK/repos/yookassa-payments-swift/browse/YooKassaPayments.podspec
https://git.yoomoney.ru/projects/SDK/repos/yookassa-payments-swift/browse/YooKassaPayments/Private/Services/Analytics/CommonTracker.swift

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to activate AppMetrica; AppMetrica has already been started'
`

How to handle such situation? Can the activation of the AppMetrica SDK be separated?

### 🔍 Reproducing the issue

1. Add AppMetrica to the app dependency with Cocoapods.
2. Use the other dependency SDK which also uses AppMetrica
3. Active AppMetrica on app launch
4. Call 3rd party sdk method which also activates AppMetrica

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
...
- YooKassaPayments (6.16.0):
    - AppMetricaAnalytics (~> 5.2.0)
    - MoneyAuth (~> 10.13.0)
    - SPaySDK (~> 1.0.8)
    - YooKassaPaymentsApi (~> 2.22.0)
    - YooKassaWalletApi (~> 2.6.0)
    - YooMoneyCoreApi (~> 3.1)
    - YooMoneySessionProfiler (~> 5.0.4)
    - YooMoneyUI (~> 7.7)
...
- AppMetrica_FMDB (5.2.0)
  - AppMetrica_Protobuf (5.2.0)
  - AppMetricaAdSupport (5.2.0):
    - AppMetricaCore (= 5.2.0)
    - AppMetricaCoreExtension (= 5.2.0)
  - AppMetricaAnalytics (5.2.0):
    - AppMetricaAdSupport (= 5.2.0)
    - AppMetricaCore (= 5.2.0)
    - AppMetricaCrashes (= 5.2.0)
    - AppMetricaWebKit (= 5.2.0)
  - AppMetricaCore (5.2.0):
    - AppMetrica_FMDB (= 5.2.0)
    - AppMetrica_Protobuf (= 5.2.0)
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaEncodingUtils (= 5.2.0)
    - AppMetricaHostState (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
    - AppMetricaNetwork (= 5.2.0)
    - AppMetricaPlatform (= 5.2.0)
    - AppMetricaProtobufUtils (= 5.2.0)
    - AppMetricaStorageUtils (= 5.2.0)
  - AppMetricaCoreExtension (5.2.0):
    - AppMetricaCore (= 5.2.0)
    - AppMetricaStorageUtils (= 5.2.0)
  - AppMetricaCoreUtils (5.2.0):
    - AppMetricaLog (= 5.2.0)
  - AppMetricaCrashes (5.2.0):
    - AppMetricaCore (= 5.2.0)
    - AppMetricaCoreExtension (= 5.2.0)
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaEncodingUtils (= 5.2.0)
    - AppMetricaHostState (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
    - AppMetricaPlatform (= 5.2.0)
    - AppMetricaProtobufUtils (= 5.2.0)
    - AppMetricaStorageUtils (= 5.2.0)
    - KSCrash/Recording (= 1.17.0)
    - KSCrash/Recording/Tools
  - AppMetricaEncodingUtils (5.2.0):
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
    - AppMetricaPlatform (= 5.2.0)
  - AppMetricaHostState (5.2.0):
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
  - AppMetricaLog (5.2.0)
  - AppMetricaNetwork (5.2.0):
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
    - AppMetricaPlatform (= 5.2.0)
  - AppMetricaPlatform (5.2.0):
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
  - AppMetricaProtobufUtils (5.2.0):
    - AppMetrica_Protobuf (= 5.2.0)
  - AppMetricaStorageUtils (5.2.0):
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
  - AppMetricaWebKit (5.2.0):
    - AppMetricaCore (= 5.2.0)
    - AppMetricaCoreUtils (= 5.2.0)
    - AppMetricaLog (= 5.2.0)
...
```

</details>

**Comment by GLinnik21** [comment]
Hey there! It seems like you're facing a classic conflict when multiple SDKs try to activate AppMetrica simultaneously. Normally, third-party SDKs should avoid activating the main AppMetrica SDK and should use reporters instead. This approach prevents the SDKs from clashing over activation and allows each to send data independently without interference.

Here are a couple of steps you can take:

1. **Reach Out to YooKassa:** Suggest that they switch to using AppMetrica's reporter mechanism. This change will allow them to send analytics data using your app's main AppMetrica activation without trying to activate it themselves.

2. **Use Reporters in Your App:** If modifying YooKassa's SDK isn't an option, you can adapt your application to utilize reporters for sending data to AppMetrica. This way, your app can avoid the initialization conflict and continue to operate smoothly. **It's important to note**, however, that using reporters doesn't include some features like _session tracking_, crash-report analytics, etc., as these require the SDK to be initialized directly.

https://github.com/appmetrica/appmetrica-sdk-ios/blob/766808009096e0e6f0648fbaf1b5460508b6c3ae/AppMetricaCore/Sources/include/AppMetricaCore/AMAAppMetrica.h#L256-L274

This should help you manage multiple data streams without the crash issue. Good luck!

**Comment by aserdobintsev** [comment]
@GLinnik21 Thanks! At least I have options to handle this now.

It would be useful to add this information to the site's documentation or troubleshooting section, because that was the first place I searched.
Also, I don't think YooKassa did it intentionally. It could be a good idea to add a separate section for SDK developers and describe how to use AppMetrica without clashing with the host app's AppMetrica activation.

Thanks again for your quick and thoughtful response!
