### ISSUE TITLE
Wrong order and set of events sent to Dashboard

### ISSUE THREAD

**Issue by TopIvanAbramov** [appmetrica/appmetrica-sdk-ios#16]
### 📚 AppMetrica SDK Version

4.5.2

### 🛠️ Xcode Version

15.2

### 📱 Device Information

iPhone 13 pro

### ⚙️ Installation Method

Swift Package Manager

### 📝 Issues

1. Dashbord shows events not in the order they occurred, I pressed to sort by time. For instance, the highlighted event occurred not between 9:31:51, but after

2. There are extra events showed in the dash. For instance, there are two events **promo_prmMain_bigBannerBlock_bannerBlock_swipe** sent at 9:31:59.  But locally in the logs we see that there is exactly one event send to AppMetrica

![image (1)](https://github.com/appmetrica/appmetrica-sdk-ios/assets/42469397/ce13cf4e-22e3-43cd-ba12-a4d5d3134627)

**Comment by GLinnik21** [comment]
Hi!
It looks like you're using AppMetrica SDK version 4.5.2. Version 4.x of AppMetrica is no longer being updated or supported. I recommend upgrading to version 5.x, which includes various bug fixes and improvements that might resolve your issue. After upgrading, check if the problem persists. If it does, you can reopen the issue for further investigation.

Feel free to follow the [AppMetrica migration guide](https://appmetrica.io/docs/en/sdk/ios/analytics/migration-io-5-0-0) for assistance with the update.

**Comment by TopIvanAbramov** [comment]
we updated the library and bug disappeared!
