### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by PollyVern** [appmetrica/appmetrica-sdk-ios#18]
### 📚 AppMetrica SDK Version

4.5.2

### 🛠️ Xcode Version

15.4

### 📱 Device Information

Apple Vision Pro Simulator

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

Good afternoon. I'm trying to run the visionOS simulator, but I get an error in the YandexMobile libraries that there is no support for this platform. What can I do to fix this?

<img width="786" alt="Снимок экрана 2024-06-19 в 12 07 53" src="https://github.com/appmetrica/appmetrica-sdk-ios/assets/68129686/a7f84c22-d39f-477b-96f5-470a2cd9e558">

### 🔍 Reproducing the issue

1. Remove default "Apple Vision (Designed for iPad)"
2. Add "Apple Vision"
3. Set Apple Vision Pro simulator and run project
4. Errors

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```

</details>

**Comment by GLinnik21** [comment]
Hello! 
Unfortunately, the 4.x version of the AppMetrica SDK does not support visionOS, and there won't be any updates for this version.

The official 5.x version does not support visionOS through Swift Package Manager or CocoaPods. However, you might try compiling it locally to see if you can get it to work. We are planning to include support for visionOS, but it will only be available in the 5.x version. 

Thank you for understanding, and we appreciate your patience!
