### ISSUE TITLE
Fastlane plugin is non-compatible with bundled helper CLI

### ISSUE THREAD

**Issue by gpinigin** [appmetrica/appmetrica-sdk-ios#21]
### 📚 AppMetrica SDK Version

5.7.0

### 🛠️ Xcode Version

15.4

### 📱 Device Information

iPhone 15

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

Latest fastlane plugin requires version of the helper CLI to match "~> 0.0", but the actual version of bundled helper is 1.0.0.0

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Fastlane integration:

upload_symbols_to_appmetrica(
    post_api_key: ENV["APPMETRICA_POST_API_KEY"],
    binary_path: ENV["HOME"] + "/SwiftPackages/checkouts/appmetrica-sdk-ios/AppMetricaCrashes/helper"
)
```

```
// Fastlane error:

[!] Your 'helper' is outdated, please upgrade to at least version ~> 0.0 and start again!
#######################################################################
```

</details>

**Comment by GLinnik21** [comment]
Hi!
Thank you for reporting this issue. We're aware of the fastlane plugin version mismatch and are working on a solution. However, as this doesn't directly relate to the AppMetrica SDK functionality, I'm closing this issue. Please feel free to open new issues for any SDK-specific concerns.
