### ISSUE TITLE
Xcode 16, problem with SPM Package

### ISSUE THREAD

**Issue by BOTTAK** [appmetrica/appmetrica-sdk-ios#22]
### 📚 AppMetrica SDK Version

5.8.0

### 🛠️ Xcode Version

Version 16.0 (16A242d)

### 📱 Device Information

iPhone 16

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

Проблема в зависимости KSCrashMonitor_CPPException.cpp 
![Снимок экрана 2024-09-17 в 19 14 23](https://github.com/user-attachments/assets/2aa6fd03-e5ff-4bb3-92f0-532018535bb4)

### 🔍 Reproducing the issue

Установить пакет через SPM :  https://github.com/appmetrica/appmetrica-sdk-ios

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

{
  "originHash" : "013e68ebe1635f3193eba6215ed1e4159e0da287b7e6cfb296dd84c094d4631e",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "194a6706acbd25e4ef639bcaddea16e8758a3e27",
        "version" : "1.2024011602.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "21fe1af9be463a359aaf8d96789ef73fc3760d09",
        "version" : "11.0.1"
      }
    },
    {
      "identity" : "appmetrica-sdk-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/appmetrica/appmetrica-sdk-ios",
      "state" : {
        "revision" : "b7c28eb99c41d2c0caa9cf7d4beac7c597578188",
        "version" : "5.8.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "1fc52ab0e172e7c5a961f975a76c2611f4f22852",
        "version" : "11.2.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "07a2f57d147d2bf368a0d2dcb5579ff082d9e44f",
        "version" : "11.1.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "617af071af9aa1d6a091d59a202910ac482128f9",
        "version" : "10.1.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "53156c7ec267db846e6b64c9f4c4e31ba4cf75eb",
        "version" : "8.0.2"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "f56d8fc3162de9a498377c7b6cea43431f4f5083",
        "version" : "1.65.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "a2ab612cb980066ee56d90d60d8462992c07f24b",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "kscrash",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kstenerud/KSCrash",
      "state" : {
        "revision" : "06b35a3cde97f23aa58b09a52ec0a986c017b751",
        "version" : "2.0.0-rc.2"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "edb6ed4919f7756157fe02f2552b7e3850a538e5",
        "version" : "1.28.1"
      }
    }
  ],
  "version" : 3
}

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```

</details>

**Comment by alexklints** [comment]
Привет.
Спасибо за репорт. Мы постараемся локализовать проблему и исправить.

**Comment by BOTTAK** [comment]
Проблема решилась таким способом: 
![Снимок экрана 2024-09-18 в 12 35 43](https://github.com/user-attachments/assets/0bbec854-aaf1-4771-b282-e4194b47652d)
После этого появится ошибка как [тут](https://github.com/appmetrica/appmetrica-sdk-ios/issues/19), она решается так: 
![Снимок экрана 2024-09-18 в 12 36 59](https://github.com/user-attachments/assets/9b583ed1-5af9-45b9-9368-d039f0aa66fe)

**Comment by aoleynik812** [comment]
Проверил на новом проекте с appmetrica-5.8.0 - все собралось без ошибок. 

Мой Package.resolved
```{
  "originHash" : "4acefa97f69090b10669f92b3335afe8522c53d2f32ef65028575ae3d4d98235",
  "pins" : [
    {
      "identity" : "appmetrica-sdk-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/appmetrica/appmetrica-sdk-ios",
      "state" : {
        "revision" : "b7c28eb99c41d2c0caa9cf7d4beac7c597578188",
        "version" : "5.8.0"
      }
    },
    {
      "identity" : "kscrash",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kstenerud/KSCrash",
      "state" : {
        "revision" : "06b35a3cde97f23aa58b09a52ec0a986c017b751",
        "version" : "2.0.0-rc.2"
      }
    }
  ],
  "version" : 3
}
```


[KSCrash-2.0.0-rc.2](https://github.com/kstenerud/KSCrash/releases/tag/2.0.0-rc.2) уже содержит эти фиксы
https://github.com/kstenerud/KSCrash/blob/06b35a3cde97f23aa58b09a52ec0a986c017b751/Sources/KSCrashRecording/Monitors/KSCrashMonitor_CPPException.cpp#L41
https://github.com/kstenerud/KSCrash/blob/06b35a3cde97f23aa58b09a52ec0a986c017b751/Sources/KSCrashRecordingCore/KSMachineContext.c#L31-L33

Могу предложить попробовать удалить $HOME/Library/Developer/Xcode/DerivedData/
