### ISSUE TITLE
invalid tracking information when submit the app in App store 

### ISSUE THREAD

**Issue by rohanvasundhara** [appmetrica/appmetrica-sdk-ios#24]
### 📚 AppMetrica SDK Version

5.0.0

### 🛠️ Xcode Version

15.0

### 📱 Device Information

iPhone 15

### ⚙️ Installation Method

CocoaPods

### 📝 Description

ITMS-91107: Invalid tracking information - A Privacyinfo.xcprivacy file contains invalid tracking information at the following path: "Frameworks/AppMetricaCore.framework/AppMetricaCore. bundle/PrivacyInfo.xcprivacy". In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content.
NSPrivacy Tracking must be true if NSPrivacyTrackingDomains isn't empty. Keys and values in any privacy
manifest
must be valid. For more details, visit: https://developer.apple.com/
documentation/bundleresources/privacy manifest files
and
https://developer.apple.com/
documentation/bundleresources/privacy manifest files/adding a privacy manifest to your
app or third-party sdk.
Apple Developer Relations

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```

</details>

**Comment by NesterovichAlexey** [comment]
Duplicate https://github.com/appmetrica/appmetrica-sdk-ios/issues/20

Hi, @rohanvasundhara! You need to update your AppMetrica version to [5.8.0](https://github.com/appmetrica/appmetrica-sdk-ios/releases/tag/5.8.0), this problem was fixed there.

**Comment by NesterovichAlexey** [comment]
Duplicate of https://github.com/appmetrica/appmetrica-sdk-ios/issues/20
