### ISSUE TITLE
App Crashes in background on this line: 18 -[YMMUserDefaultsStorage setBool:forKey:]

### ISSUE THREAD

**Issue by HappyIosDeveloper** [appmetrica/appmetrica-sdk-ios#6]
### 📚 AppMetrica SDK Version

2.9.6

### 🛠️ Xcode Version

Version 15.1 (15C65)

### 📱 Device Information

17.2.1 (21C66)

### ⚙️ Installation Method

CocoaPods

### 📝 Description

App crashes on the background, the only footprint I have is this image:

![Screenshot 2023-12-30 at 10 25 37 AM](https://github.com/appmetrica/appmetrica-sdk-ios/assets/29095193/d2063491-06bb-4543-993e-e8cc7d1af6f4)

**Comment by GLinnik21** [comment]
Unfortunately, we do not have a long-term support (LTS) version of AppMetrica available. Therefore, we recommend updating to the latest release version to see if this resolves the issue.
