### ISSUE TITLE
AppMetricaConfiguration.logs = false Не отключает логи  консоли

### ISSUE THREAD

**Issue by matvei-lp** [appmetrica/appmetrica-sdk-ios#7]
### 📚 AppMetrica SDK Version

5.0.0-beta.1

### 🛠️ Xcode Version

Version 15.0.1 (15A507)

### 📱 Device Information

MacOS Sonoma 14.2.1

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

Установка флага не отключает логи консоли

 if let configuration = AppMetricaConfiguration(apiKey: "") {
            configuration.logs = false
            AppMetrica.activate(with: configuration)
    }

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>

```
+[AMAQueuesFactory serialQueueForIdentifierObject:domain:]:17 Queue created: io.appmetrica.CoreUtils.AMAUrgentEventCountDispatchStrategy.Queue
+[AMAQueuesFactory serialQueueForIdentifierObject:domain:]:17 Queue created: io.appmetrica.CoreUtils.AMAEventCountDispatchStrategy.Queue
+[AMAQueuesFactory serialQueueForIdentifierObject:domain:]:17 Queue created: io.appmetrica.CoreUtils.AMATimerDispatchStrategy.Queue
-[AMACancelableDelayedExecutor cancelDelayed]:121 Cancellation of async execution on queue: <OS_dispatch_queue_serial: io.appmetrica.CoreUtils.AMATimerDispatchStrategy.Queue>
-[AMACancelableDelayedExecutor executeAfterDelay:block:]:90 Delayed (90.00) async execution on queue: <OS_dispatch_queue_serial: io.appmetrica.CoreUtils.AMATimerDispatchStrategy.Queue>
-[AMATimer createTimerSourceAndStart]:54 Timer started, timeout: 90.00```

**Comment by GLinnik21** [comment]
Duplicate of #5

**Comment by GLinnik21** [comment]
Здравствуйте. Решили проблему [тут](https://github.com/appmetrica/appmetrica-sdk-ios/issues/5#issuecomment-1845299783). Сделал `5.0.0-beta.2` для удобства интегрирования. Попробуйте исправит ли это ошибку.
