### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by easydev991** [appmetrica/appmetrica-sdk-ios#9]
### 📚 AppMetrica SDK Version

5.1.0

### 🛠️ Xcode Version

15.3

### 📱 Device Information

iPhone 13 Pro

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

There is no examples of integration, no documentation at all for those transitioning from the old library (4.3*)

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```

</details>

**Comment by GLinnik21** [comment]
Hey there! Sorry to hear you're having trouble finding the documentation you need. We do have some resources available for transitioning from the old library (4.3*), but they're currently only in Russian. You can check them out here: https://appmetrica.io/docs/ru/sdk/ios/analytics/migration-io-5-0-0.

If you're still stuck or need help in English, don't hesitate to reach out to our support team. They're always ready to lend a hand. Here's the link to get in touch: https://appmetrica.io/docs/en/troubleshooting/feedback-new

Hope this helps, and best of luck with your integration!

**Comment by GLinnik21** [comment]
I'm closing this issue since it's not related to the SDK.

**Comment by GLinnik21** [comment]
Hi! I have an update on the English documentation. The English version of the documentation has been recently released. You can access it at https://appmetrica.io/docs/en/sdk/ios/analytics/migration-io-5-0-0.
